---

- name: conf dir creation
  file:
    path: /etc/orchestrator-dashboard
    state: directory

- name: db directory creation
  file:
    path: /etc/mysql
    state: directory

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/mysql/db_data
    - /etc/mysql/utils
  when: with_db == True

- name: download sql file from github
  get_url:
    url: 'https://raw.githubusercontent.com/maricaantonacci/orchestrator-dashboard/add_db/utils/orchestrator_dashboard.sql'
    dest: '/etc/mysql/utils'
  when: with_db == True

- name: set up config file
  template:
    src=config.json.j2 dest="{{ dest_conf }}/config.json"
  when: with_db == True

- name: set up config file for dash with db
  template:
    src=config_db.json.j2 dest="{{ dest_conf }}/config.json"
  when: with_db == False

- name: set up env db file
  template:
    src=mysqlenv.j2 dest="{{ dest_conf }}/mysqlenv"
  when: with_db == True

- name: git clone tosca
  git:
    repo: "{{ tosca_dash_conf }}"
    dest: /opt/laniakea-dashboard-config
 
- name: start db container container
  docker_container:
    name: orchestrator-dashboard-db
    image: "{{ db_image }}"
    state: started
    ports:
      - "3306:3306"
    detach: yes
    env_file: "{{ dest_conf }}/mysqlenv"
    volumes:
      - "{{ dest_conf }}/db_data:/var/lib/mysql"
      - "{{ dest_conf }}/utils/:/docker-entrypoint-initdb.d"  
  when: with_db == True
    
- name: start dash container
  docker_container:
    name: orchestrator-dashboard
    image: "{{ dash_image }}"
    state: started
    ports:
      - "443:5001"
    detach: yes
    env:
      ENABLE_HTTPS: "True"
    volumes:
      - "/etc/letsencrypt/live/{{ dash_fqdn }}/privkey.pem:/certs/key.pem"
      - "/etc/letsencrypt/live/{{ dash_fqdn }}/cert.pem:/certs/cert.pem"
      - "{{ dest_conf }}/config.json:/app/app/config.json"
      - "/opt/laniakea-dashboard-config/tosca-templates:/opt/tosca-templates"
